# This is a basic workflow to help you get started with Actions

name: Setting up DNS on Raspberry Pi 
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest, Linux

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Update Raspberry Pi 
    - name: Update Raspberru Pi 
      run: |
        sudo apt update 
        sudo apt upgrade 
  

    # Installing DNSmasq 
    - name: Install DNSmasq 
      run:  sudo apt install dnsmasq 
      
      
    
    #Configuring DNS server 
    - name: Configuring DNS Server 
      run: |
        sudo nano /etc/dnsmasq.conf 
        
        
